remove grep -z, busybox cries

diff --git a/milpa b/milpa
--- a/milpa
+++ b/milpa
@@ -20,6 +20,11 @@ if [[ ! -d "$MILPA_ROOT" ]]; then
   exit 78
 fi
 
+if [[ ! -d "$MILPA_ROOT/.milpa" ]]; then
+  >&2 echo "MILPA_ROOT is not setup properly: missing .milpa folder: $MILPA_ROOT"
+  exit 78
+fi
+
 # bash is fine and all, but we need a little helper to run parsing for us
 export MILPA_COMPA="${MILPA_COMPA:-$MILPA_ROOT/compa}"
 # bail early if we're autocompleting
@@ -56,7 +61,7 @@ function @milpa.load_util () {
     if [[ "${!env_name}" != "1" ]]; then
       # util not found
       >&2 echo "Missing util named $util_name in ${libpath[*]}"
-      exit 78
+      exit 70 # programmer error
     fi
   done
 }
@@ -73,9 +78,6 @@ compaOut=$(mktemp -t "compaOut.XXX")
 compaErr=$(mktemp -t "compaErr.XXX")
 trap 'rm -rf $compaOut $compaErr' ERR EXIT TERM
 
-if ! printf '%s\0' "${@}" | grep -Fqxz -- '--silent'; then
-  @milpa.log debug "Calling out compa with ${*}"
-fi
 # figure out what the user is asking for
 COMPA_OUT="$compaOut" "$MILPA_COMPA" "$@" 2>"$compaErr" || {
   exitCode=$?
